// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcD90UTYBzAmF0qzRqYiBgJ-9ul2s_LQQ',
    appId: '1:1082483227170:android:07a1db25f43aebcc8aa87b',
    messagingSenderId: '1082483227170',
    projectId: 'seatup-ecb21',
    storageBucket: 'seatup-ecb21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUEk6ZdjqD2C2_YQ43GG0JD2Aqffw-emA',
    appId: '1:1082483227170:ios:fc6c842fcb2f0e388aa87b',
    messagingSenderId: '1082483227170',
    projectId: 'seatup-ecb21',
    storageBucket: 'seatup-ecb21.firebasestorage.app',
    androidClientId: '1082483227170-6sskk71n0o9c34r0valrrmbjkclflpdg.apps.googleusercontent.com',
    iosClientId: '1082483227170-q9sn3tssl5kloo2ao041vqhvsemcpvqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.seatupApp',
  );
}
